name: Pull Request Build
on: [ pull_request ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17, 18 ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Capture build artifacts
        if: ${{ runner.os == 'Windows' && matrix.java == '17' }} # Only upload artifacts built from one OS and java version
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
